exe2b.exe: matriximp.o  maximumimp.o app.o
	g++ -o exe2b.exe matriximp.o maximumimp.o app.o
maximumimp.o: maximumimp.cpp
	g++ -c maximumimp.cpp
matriximp.o: matriximp.cpp
	g++ -c matriximp.cpp
app.o: app.cpp
	g++ -c app.cpp
