E-Device.exe:E-Device.o Lap.o Mobile.o App.o
	g++ -o E-Device.exe E-Device.o  Lap.o Mobile.o App.o
E-Device.o:E-Device.cpp
	g++ -c E-Device.cpp
Lap.o:Lap.cpp
	g++ -c Lap.cpp
Mobile.o:Mobile.cpp
	g++ -c Mobile.cpp
App.o:App.cpp
	g++ -c App.cpp
