exe2a.exe: sortimp.o  reverseimp.o app.o
	g++ -o exe2a.exe sortimp.o reverseimp.o app.o
reverseimp.o: reverseimp.cpp
	g++ -c reverseimp.cpp
sortimp.o: sortimp.cpp
	g++ -c sortimp.cpp
app.o: app.cpp
	g++ -c app.cpp
