armstrong.exe:armstrongimp.o armstrongapp.o
	cc -o armstrong.exe armstrongimp.o armstrongapp.o -lm
armstrongimp.o:armstrongimp.c
	cc -c armstrongimp.c
armstrongapp.o:armstrongapp.c
	cc -c armstrongapp.c
