exe5.exe:L_Stack_L_Queue_app.o L_Stack_L_Queue_imp.o
	g++ L_Stack_L_Queue_app.o L_Stack_L_Queue_imp.o -o exe5.exe
L_Stack_L_Queue_app.o:L_Stack_L_Queue_app.cpp
	g++ -c L_Stack_L_Queue_app.cpp
L_Stack_L_Queue_imp.o:L_Stack_L_Queue_imp.cpp
	g++ -c L_Stack_L_Queue_imp.cpp
