switchcalc.exe:switchcalcimp.o switchcalcapp.o
	cc switchcalcimp.o switchcalcapp.o -o switchcalc.exe
switchcalcimp.o:switchcalcimp.c
	cc -c switchcalcimp.c
switchcalcapp.o:switchcalcapp.c
	cc -c switchcalcapp.c
