app.exe:numericimp.o arrayimp.o app.o
	g++ app.o numericimp.o arrayimp.o -o app.exe
app.o:app.cpp
	g++ -c app.cpp
numericimp.o:numericimp.cpp
	g++ -c numericimp.cpp
arrayimp.o:arrayimp.cpp
	g++ -c arrayimp.cpp
